# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

CFLAGS += -D__USE_MINGW_ANSI_STDIO=1

obj-y += source/msw/buffer.o
obj-y += source/msw/cache.o
obj-y += source/msw/path.o
obj-y += source/msw/sysfs.o
obj-y += source/msw/thread.o
