# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

obj-y += source/x86-64/paging.o

obj-y += source/cpuid/cache.o
obj-y += source/cpuid/cpuid.o
obj-y += source/cpuid/amd/cache.o
obj-y += source/cpuid/amd/cpuid.o
obj-y += source/cpuid/intel/cache.o
obj-y += source/cpuid/intel/cpuid.o
