# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

obj-y += source/posix/buffer.o
obj-y += source/posix/cache.o
obj-y += source/posix/path.o
obj-y += source/posix/sysfs.o
obj-y += source/linux/thread.o
